vscode:
  extensions:
    - humao.rest-client@0.23.0:JNawNa9Juht3Bl5xY2refg==
image:
  file: .gitpod.Dockerfile

tasks:
  - before: export DANGEROUSLY_DISABLE_HOST_CHECK=true
  - init: npm install
    command: cd web
  - command: npm start

ports:
  - port: 3000
    onOpen: open-preview